version: '3'

services:
  backend:
    container_name: backend
    build: 
      context: backend
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - '4000:3000'
    depends_on:
      - postgres
    restart: always
  frontend:
    container_name: frontend
    build: 
      context: frontend
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - '3001:3000'
    restart: always
  postgres:
    container_name: postgres
    image: postgres:14-alpine
    env_file: .env
    restart: always
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres  