version: '3'

services:
  backend:
    container_name: backend
    build: 
      context: backend
      dockerfile: Dockerfile.pub
    image: backend-release  
    env_file: .env
    ports:
      - 4000:3001
    depends_on:
      - postgres
    restart: always
    networks:
      - backend

  frontend:
    container_name: frontend
    build: 
      context: frontend
      dockerfile: Dockerfile.pub
    image: frontend-release
    ports:
      - 80:3000
    restart: always
    networks:
      - frontend

  postgres:
    container_name: postgres
    image: postgres:14-alpine
    env_file: .env
    restart: always
    volumes:
      - postgres_data:/data/postgres
    networks:
      - backend

  adminer:
    image: adminer
    restart: always
    ports:
      - 8008:8080
    depends_on:
      - postgres
    networks:
      - backend
volumes:
  postgres_data:
networks:
  backend:
  frontend:           